**Please upload the completed notebook to Brightspace** under `Computer Vision > Assignment submission`

# Numpy

This notebook includes `numpy` exercises focussing on `broadcasting` and `dot products`.

As in most notebooks, we'll start with some imports of modules that we will need:

In [32]:
import numpy as np

## Broadcasting and indexing

The cell below generates an array of random numbers:

In [33]:
x = np.random.random((10,14))
x.shape

(10, 14)

Below, create two random vectors `y` and `z`, whose shapes are such, that the operations in the next cell do not produce any errors:

In [34]:
#YOUR_CODE_HERE
y = np.random.random((10, 14))
z = np.random.random((10, 14))

In [35]:
# test operations
_ = x + y
_ = x + (y * z)

Now, let's try with the following vectors `a` and `b`:

In [36]:
a = np.random.random((5,5))
b = np.arange(5)
a

array([[0.75397759, 0.93454712, 0.5493789 , 0.32610075, 0.41097695],
       [0.62980151, 0.47328238, 0.03431155, 0.1777824 , 0.03602698],
       [0.7866311 , 0.7971395 , 0.90482279, 0.55132375, 0.70464789],
       [0.17271054, 0.50380711, 0.44658138, 0.4739689 , 0.44448106],
       [0.61258186, 0.12498073, 0.16600625, 0.20390063, 0.75332189]])

In the cell below perform two operations: (1) add `b` to the rows of `a`, (2) add `b` to the columns of `a`:

In [37]:
# adding to the rows
row_sum = (a.T + b).T
print(row_sum)
# adding to the columns
col_sum = a + b
print(col_sum)

[[0.75397759 0.93454712 0.5493789  0.32610075 0.41097695]
 [1.62980151 1.47328238 1.03431155 1.1777824  1.03602698]
 [2.7866311  2.7971395  2.90482279 2.55132375 2.70464789]
 [3.17271054 3.50380711 3.44658138 3.4739689  3.44448106]
 [4.61258186 4.12498073 4.16600625 4.20390063 4.75332189]]
[[0.75397759 1.93454712 2.5493789  3.32610075 4.41097695]
 [0.62980151 1.47328238 2.03431155 3.1777824  4.03602698]
 [0.7866311  1.7971395  2.90482279 3.55132375 4.70464789]
 [0.17271054 1.50380711 2.44658138 3.4739689  4.44448106]
 [0.61258186 1.12498073 2.16600625 3.20390063 4.75332189]]


Finally, consider the folloiwng array `c`:

In [38]:
c = np.random.randn(3,5,7,9,11,13,17)
c.shape

(3, 5, 7, 9, 11, 13, 17)

In the cell below use indexing to select the 2nd slice along axis 1, the last slice along axis 5, and all numbers along the remaining axes/dimensions, reversing the order along the last axis. Try to make your indexing as compact as possible:

In [39]:
#YOUR_CODE_HERE
c[:, 1, :, :, :, -1, ::-1]

array([[[[[-4.26231863e-01,  1.25564029e-01, -4.26227321e-01, ...,
           -3.85776247e-01, -4.00210879e-01, -1.18993159e-01],
          [-4.10993390e-01,  3.87463433e-01,  1.01933408e+00, ...,
            1.30826678e+00,  6.66301610e-01, -7.41405255e-02],
          [-1.07489263e+00,  1.42839891e+00,  7.05825393e-01, ...,
           -7.70926732e-01, -3.93908040e-02, -6.41923926e-01],
          ...,
          [ 8.32359684e-01, -7.68037281e-01, -1.28444066e+00, ...,
           -1.22279840e-01, -3.34369862e-01,  7.01119614e-01],
          [ 9.67455397e-01,  5.29609984e-01,  7.01153610e-01, ...,
           -7.94594679e-01,  1.10008973e+00,  4.22754154e-01],
          [-1.92075825e-01, -1.30895691e-01, -1.55432963e+00, ...,
           -5.65202110e-01,  4.33553637e-01,  7.20085825e-01]],

         [[ 8.81472078e-01,  1.61586288e+00,  8.73511585e-01, ...,
            5.78933725e-01,  4.37049839e-01,  1.16044552e+00],
          [ 1.85821720e+00, -3.91378776e-01, -1.22349951e+00, ...,
      

## Dot products

In [40]:
u = np.random.randn(111,17)
v = np.random.random((17,2))
u.shape, v.shape

((111, 17), (17, 2))

Answer the following questions:

- Are the two shapes compatible when it comes to the dot product (i.e. can you multiply them)?
- If so, what would be the shape of their dot product?

In the cell below, try to multiply `u` and `v`, and see if your answers were correct:

In [41]:
#YOUR_CODE_HERE
w = u @ v

What about multiplying `v` and `u`? Will this work?

Try in the cell below:

In [42]:
#YOUR_CODE_HERE
w2 = v @ u

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 111 is different from 2)

If the above didn't work for you, is there a way of multiplying `v` by `u`?

Look at their shapes again:

In [43]:
v.shape, u.shape

((17, 2), (111, 17))

Is there an operation which can make them compatible for dot product?

In the cell below, examine the shape of the transpose of both `v` and `u`:

In [44]:
#YOUR_CODE_HERE
v.T.shape, u.T.shape

((2, 17), (17, 111))

Can you multiply them now? If so, what is going to be the shape of the result?

In [45]:
#YOUR_CODE_HERE
w2 = v.T @ u.T

What do the dot products of `u` and `v`, and `v` and `u` have in common?

In [46]:
#YOUR_ANSWER_HERE
(u @ v).T == v.T @ u.T  # might not give all 'True' answer due to round-off error

# np.max(np.abs((u @ v).T - v.T @ u.T))  # this should be very small though, at the order of 8e-16

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  Tru

If you've answered correctly then congratulations, you have discovered one of the basic rules of linear algebra!